---
Log:
  Level: debug
  AccessPath: ./access.log
  ErrorPath: ./error.log
DnsConfigPath: ./dns.json
Nodes:
  - PanelType: V2board
    ApiConfig:
      ApiHost: https://cloud.mioowo.dev/
      ApiKey: 788u7tyte73jd72m1270
      NodeID: 1
      NodeType: V2ray
      Timeout: 30
      EnableVless: false
      EnableXTLS: false
    ControllerConfig:
      ListenIP: 0.0.0.0
      UpdatePeriodic: 60
      EnableDNS: false
      CertConfig:
        CertMode: dns
        CertDomain: unioreo.rip
        Provider: cloudflare
        Email: 3210596730@qq.com
        DNSEnv:
          CF_DNS_API_TOKEN: odlZ9HIUDll44ws87XS8hdBtsieQzcc9t4KG__fr
